services:
  zookeeper:
    image: zookeeper:latest
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181

  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'